### ISSUE TITLE
only can update the code but can rerun the project

### ISSUE THREAD

**Issue by wangyijunjunjun** [kelvv/hot-deploy#2]
I mean this tool can just update the code , 
but can't execute command like pm2 restart

**Comment by kelvv** [comment]
yeah , you need to use  like  pm2 start --watch  to restart your project

should i add complete interface? give you an interface to exec cmd

**Comment by wangyijunjunjun** [comment]
@kelvv thanks for your response 
I mean can it do it automatically？

**Comment by kelvv** [comment]
@wangyijunjunjun  Thank you 

you should config 'pm2 watch' by yourself because you need to let pm2 know two point:
1.which file you need to watch (.html , .js)
2.which file you need to ignore (.json , .config)

I want to support an interface to restart app at next version,you can set 'pm2 restart' or else

**Comment by kelvv** [comment]
@wangyijunjunjun version 1.3.1 is fixed.

you can config your complateCMD in config file , just see readme , thankyou
